name = "ld50"
default_targets = ["lovejs", "win64", "macos"]
build_directory = "builds"


love_files = [
    "::git-ls-tree::",
    "-*/.*",
]

[windows.exe_metadata]
ProductName = "malbork" # "LÃ–VE"
OriginalFilename = "malbork.exe" # "love.exe"

[lovejs]
love_binaries = "C:\\Users\\George\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\Local\\makelove\\makelove\\Cache\\love-binaries\\11.3\\lovejs"

[win64]
love_binaries = "C:\\Program Files\\LOVE"